# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:59
from __future__ import unicode_literals

import combine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='archives', validators=[combine.models.validate_omex])),
                ('created', models.DateTimeField(editable=False, verbose_name='date published')),
                ('md5', models.CharField(max_length=36)),
                ('task_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
