# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:24
from __future__ import unicode_literals

import combine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='archives/upload', validators=[combine.models.validate_omex])),
                ('created', models.DateTimeField(editable=False, verbose_name='date published')),
            ],
        ),
    ]
