# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to='archives/upload'),
        ),
    ]
