language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop

install:
    - pip install -r requirements.txt
    # testing dependencies
    - pip install mock
    - pip install requests
    - pip install coverage
    - pip install coveralls

script:
    # functional test with running database server
    python manage.py test

    # - python tests/tests.py
    # - coverage run tests/tests.py

# after_success:
#    - coveralls


