language: generic
sudo: required

branches:
    only:
        - master

services:
    - docker

install:
    - docker build -t tellurium-web .
    - docker run -d -p 127.0.0.1:80:80 --name tellurium-web tellurium-web

before_script:
    # test dependencies
    - sudo pip -r install mock
    - sudo pip -r install requests
    - sudo pip -r install coverage
    - sudo pip -r install coveralls

script:
    - docker ps | grep -q tellurium-web
    - python tests.py
    - coverage run tests.py

after_success:
    - coveralls


