language: python
cache: pip
python:
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

install:
    - pip install -r requirements.txt
    # testing dependencies
    - pip install mock
    - pip install requests
    - pip install coverage
    - pip install coveralls

script:
    # functional test with running database server
    cd teweb && python manage.py test

    # - python tests/tests.py
    # - coverage run tests/tests.py

# after_success:
#    - coveralls


