sudo: required
os: linux

language: python
cache: pip
python:
  - "3.5"
  - "3.6"

env:
  - DJANGO_ADMIN_PASSWORD=test

install:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install coverage
  - pip install coveralls

script:
    # functional test with running database server
    cd teweb && python manage.py test

    # - python tests/tests.py
    # - coverage run tests/tests.py

# after_success:
#    - coveralls


