# travis only runs on ubuntu 14.04
dist: trusty
sudo: required
language: python
# cache: pip
python:
  - "3.5"
  - "3.6"

branches:
  only:
    - master
    - develop

# before_install:
#   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#   - sudo apt-get update -qq

install:
#  - sudo apt-get install -qq g++-5
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - pip install -r requirements.txt
  # testing dependencies
  - pip install mock
  - pip install requests
  - pip install coverage
  - pip install coveralls

script:
    # functional test with running database server
    cd teweb && python manage.py test

    # - python tests/tests.py
    # - coverage run tests/tests.py

# after_success:
#    - coveralls


